config/routes.rb
Rails.application.routes.draw do
  resources :items

  resources :order_suppliers

  resources :orders

  resources :products

  resources :suppliers

  resources :groups

  resources :units

  devise_for :users
  resources :users

  get '/orders/open/:id', to: 'orders#open'

#  match ':controller(/:action(/:id))', :via => [ :get, :post] 

  root to: 'visitors#index'
end

app/models/group.rb
class Group < ActiveRecord::Base
	scope :active, lambda { where(:active => true) }
	has_many :units
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
	before_action :set_group, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    authorize User
    @groups = Group.all
		@units = Unit.all
    respond_with(@groups)
  end

  def show
    authorize User
		@units = Unit.all
    respond_with(@group)
  end

  def new
    authorize User
		@units = Unit.all
    @group = Group.new
    respond_with(@group)
  end

  def edit
		@units = Unit.all
  end

  def create
    authorize User
    @group = Group.new(group_params)
    flash[:notice] = 'Group was successfully created.' if @group.save
    respond_with(@group)
  end

  def update
    authorize User
    flash[:notice] = 'Group was successfully updated.' if @group.update(group_params)
    respond_with(@group)
  end

  def destroy
    authorize User
    @group.destroy
    respond_with(@group)
  end

  private
    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :email, :telefone, :active, :dealtype, :note, :address, :error_unit_id, :acounting_unit_id, :bill_unit_id, :sw_unit_id, :acount_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :telephone %>
    <%= f.input :active %>
    <%= f.input :dealtype %>
    <%= f.input :note %>
    <%= f.input :address %>
    <br>
    <%= f.label 'Reponsables:' %>
    <br>
    <%= f.label :error_unit_id %>
    <%= f.select(:error_unit_id, @units.map {|s| [s.name, s.id]}) %>
    <%= f.label :acounting_unit_id %>
    <%= f.select(:acounting_unit_id, @units.map {|s| [s.name, s.id]}) %>
    <%= f.label :bill_unit_id %>
    <%= f.select(:bill_unit_id, @units.map {|s| [s.name, s.id]}) %>
    <%= f.label :sw_unit_id %>
    <%= f.select(:sw_unit_id, @units.map {|s| [s.name, s.id]}) %>
    <br><br>
    <%= f.input :acount_id %>
  </div>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<div class="container">
  <div class="row">
		<h3>Groups</h3>
    <div class="column">
      <table class="table">
				<thead>
					<tr>
						<th>Name</th>
						<th>Email</th>
						<th>telephone</th>
						<th>Active</th>
						<th>Dealtype</th>
						<th>Note</th>
						<th>Address</th>
						<th>Error unit</th>
						<th>Acounting unit</th>
						<th>Bill unit</th>
						<th>Sw unit</th>
						<th>Acount</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @groups.each do |group| %>
						<% if group.active?
								@cl='class=success' 
						else
								@cl='class=active' 
						end%>
						<tr <%=@cl%> >
						  <td><%= group.name %></td>
						  <td><%= group.email %></td>
						  <td><%= group.telephone %></td>
						  <td><%= group.active %></td>
						  <td><%= group.dealtype %></td>
						  <td><%= group.note %></td>
						  <td><%= group.address %></td>
						  <td><%= @units.find(group.error_unit_id).name %></td>
						  <td><%= @units.find(group.acounting_unit_id).name %></td>
						  <td><%= @units.find(group.bill_unit_id).name %></td>
						  <td><%= @units.find(group.sw_unit_id).name %></td>
						  <td><%= group.acount_id %></td>
						  <td><%= link_to 'Units', units_path(:group_id => group.id), :class => 'btn btn-default btn-xs'  %></td>
						  <td><%= link_to 'Show', group, :class => 'btn btn-default btn-xs' %></td>
						  <td><%= link_to 'Edit', edit_group_path(group), :class => 'btn btn-default btn-xs' %></td>
						  <td><%= link_to 'Destroy', group, :class => 'btn btn-default btn-xs', method: :delete, data: { confirm: 'Are you sure?' } %></td>

						</tr>
					<% end %>
        </tbody>
				<tr></tr>
      </table>
    </div>
  </div>
	<td>	<%= link_to 'New Group', new_group_path %> </td>
</div>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @group.email %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @group.telephone %>
</p>

<p>
  <strong>Active:</strong>
  <%= @group.active %>
</p>

<p>
  <strong>Dealtype:</strong>
  <%= @group.dealtype %>
</p>

<p>
  <strong>Note:</strong>
  <%= @group.note %>
</p>

<p>
  <strong>Address:</strong>
  <%= @group.address %>
</p>
<p>
  <strong>Responsables:</strong>
</p>
<p>
  <strong>Error unit:</strong>
  <%= @group.error_unit_id %>
</p>

<p>
  <strong>Acounting unit:</strong>
  <%= @group.acounting_unit_id %>
</p>

<p>
  <strong>Bill unit:</strong>
  <%= @group.bill_unit_id %>
</p>

<p>
  <strong>Sw unit:</strong>
  <%= @group.sw_unit_id %>
</p>

<p>
  <strong>Acount:</strong>
  <%= @group.acount_id %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>