config/routes.rb
Rails.application.routes.draw do
  resources :items

  resources :order_suppliers

  resources :orders

  resources :products

  resources :suppliers

  resources :groups

  resources :units

  devise_for :users
  resources :users

  get '/orders/open/:id', to: 'orders#open'

#  match ':controller(/:action(/:id))', :via => [ :get, :post] 

  root to: 'visitors#index'
end

app/models/order.rb
class Order < ActiveRecord::Base
	scope :sort, lambda { order('date DESC') }
	has_many :order_suppliers
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:open, :show, :edit, :update, :destroy]

  respond_to :html

  def index
    @orders = Order.sort
    respond_with(@orders)
  end

  def open
		@suppliers=OrderSupplier.select(:supplier_id).where(:order_id=>params[:id])
		@products=Product.where(supplier_id: @suppliers, :active => true)
		@products.each do |product|
			if Item.where(:product_id=>product.id, :order_id=>params[:id]).exists?
				logger.debug(product.name)
			else
				@item=Item.new()
				@item.order_id=params[:id]
				@item.product_id=product.id
				@item.supplier_id=product.supplier_id
				@item.name=product.name
				@item.note=product.note
				@item.minall=product.minall
				@item.mingroup=product.mingroup
				@item.kgxunit=product.kgxunit
				@item.unittype=product.unittype
				@item.price=product.price
				@item.save
				logger.debug(product.name+ 'new')
			end
		end
 		if @order.state!='Open'
			@order.state='Open'
			if @order.save
	      format.html { redirect_to orders_url, notice: 'Order was successfully updated.' }
	      format.json { head :no_content }
			end
		end
	end

  def show
    respond_with(@order)
  end

  def new
    @order = Order.new
    respond_with(@order)
  end

  def edit
  end

  def create
    @order = Order.new(order_params)
    @order.save
    respond_with(@order)
  end

  def update
    @order.update(order_params)
    respond_with(@order)
  end

  def destroy
    @order.destroy
    respond_with(@order)
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:state, :date, :requested, :received, :priceini, :priceend)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :state %>
    <%= f.input :date %>
    <%= f.input :requested %>
    <%= f.input :received %>
    <%= f.input :priceini %>
    <%= f.input :priceend %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div class="container">
	<div class="row">
		<h1>Listing orders</h1>
		<div class="column">
      <table class="table">  
				<thead>
					<tr>
						<th>State</th>
						<th>Date</th>
						<th>Requested</th>
						<th>Received</th>
						<th>Priceini</th>
						<th>Priceend</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @orders.each do |order| %>
						<tr>
						  <td><%= order.state %></td>
						  <td><%= order.date.strftime('%Y/%m/%d') %></td>
						  <td><%= order.requested %></td>
						  <td><%= order.received %></td>
						  <td><%= order.priceini %></td>
						  <td><%= order.priceend %></td>
						  <td><%= link_to 'Suppliers', order_suppliers_path(:order_id => order.id), :class => 'btn btn-default btn-xs' %></td>
						  <td><%= link_to 'Show', order, :class => 'btn btn-default btn-xs' %></td>
						  <td><%= link_to 'Edit', edit_order_path(order), :class => 'btn btn-default btn-xs' %></td>
						  <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-default btn-xs' %></td>

						<% if order.state=='Open' %>
						  <td><%= link_to 'Add products', { :id => order.id, :action => 'open' }, :class => 'btn btn-default btn-xs' %></td>
						<% end %>

						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
	<br>
	<%= link_to 'New Order', new_order_path %></div>
</div>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/open.html.erb
<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State:</strong>
  <%= @order.state %>
</p>

<p>
  <strong>Date:</strong>
  <%= @order.date %>
</p>

<p>
  <strong>Requested:</strong>
  <%= @order.requested %>
</p>

<p>
  <strong>Received:</strong>
  <%= @order.received %>
</p>

<p>
  <strong>Priceini:</strong>
  <%= @order.priceini %>
</p>

<p>
  <strong>Priceend:</strong>
  <%= @order.priceend %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>