config/routes.rb
Rails.application.routes.draw do
  resources :items

  resources :order_suppliers

  resources :orders

  resources :products

  resources :suppliers

  resources :groups

  resources :units

  devise_for :users
  resources :users

  get '/orders/open/:id', to: 'orders#open'

#  match ':controller(/:action(/:id))', :via => [ :get, :post] 

  root to: 'visitors#index'
end

app/models/unit.rb
class Unit < ActiveRecord::Base
	scope :active, lambda { where(:active => true) }
	belongs_to :group
  has_many :users
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_unit, only: [:show, :edit, :update, :destroy]
	before_action :set_group, only: [:index, :new]

  respond_to :html

  def index
    authorize User
		if params[:group_id]
			@units = Group.find(params[:group_id]).units
		else
	    @units = Unit.all
		end
    respond_with(@units)
  end

  def show
    authorize User
    respond_with(@unit)
  end

  def new
    authorize User
    @unit = Unit.new(:group_id=>params[:group_id])
    respond_with(@unit)
  end

  def edit
  end

  def create
    authorize User
    @unit = Unit.new(unit_params)
    flash[:notice] = 'Unit was successfully created.' if @unit.save
    respond_with(@unit)
  end

  def update
    authorize User
    flash[:notice] = 'Unit was successfully updated.' if @unit.update(unit_params)
    respond_with(@unit)
  end

  def destroy
    authorize User
    @unit.destroy
    respond_with(@unit)
  end

  private
    def set_unit
      @unit = Unit.find(params[:id])
    end

    def set_group
      @group = Group.find(params[:group_id]) if params[:group_id]
    end


    def unit_params
      params.require(:unit).permit(:group_id, :name, :email, :telefone, :active, :note, :account_id)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= simple_form_for(@unit) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :group_id %>
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :telefone %>
    <%= f.input :active %>
    <%= f.input :note %>
    <%= f.input :account_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit, :class => 'button-xs' %>
<%= link_to 'Back', units_path, :class => 'button-xs'  %>

app/views/units/index.html.erb
<div class="container">
	<div class="row">
		<h1>Listing units</h1>
		<div class="column">
      <table class="table">
				<thead>
					<tr>
						<th>Group</th>
						<th>Name</th>
						<th>Email</th>
						<th>Telephone</th>
						<th>Active</th>
						<th>Note</th>
						<th>Account</th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody>
					<% @units.each do |unit| %>
						<% if unit.active?
								@cl='class=success' 
						else
								@cl='class=active' 
						end%>
						<tr <%=@cl%> >
						  <td><%= Group.find(unit.group_id).name %></td>
						  <td><%= unit.name %></td>
						  <td><%= unit.email %></td>
						  <td><%= unit.telephone %></td>
						  <td><%= unit.active %></td>
						  <td><%= unit.note %></td>
						  <td><%= unit.account_id %></td>
						  <td><%= link_to 'Users', users_path(:unit_id => unit.id), :class => 'btn btn-default btn-xs' %></td>
						  <td><%= link_to 'Show', unit, :class => 'btn btn-default btn-xs' %></td>
						  <td><%= link_to 'Edit', edit_unit_path(unit), :class => 'btn btn-default btn-xs' %></td>
						  <td><%= link_to 'Destroy', unit, :class => 'btn btn-default btn-xs', method: :delete, data: { confirm: 'Are you sure?' } %></td>
						</tr>
					<% end %>
		      </tbody>
					<tr></tr>
		    </table>
			</div>
		</div>
		<br>
		<%= link_to 'New Unit', new_unit_path %>
	</div>
</div>

app/views/units/new.html.erb
<h1>New unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Group:</strong>
  <%= @unit.group_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @unit.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @unit.email %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @unit.telephone %>
</p>

<p>
  <strong>Active:</strong>
  <%= @unit.active %>
</p>

<p>
  <strong>Note:</strong>
  <%= @unit.note %>
</p>

<p>
  <strong>Account:</strong>
  <%= @unit.account_id %>
</p>

<%= link_to 'Edit', edit_unit_path(@unit), :class => 'button-xs' %> |
<%= link_to 'Back', units_path, :class => 'button-xs' %>