config/routes.rb
Rails.application.routes.draw do
  resources :items

  resources :order_suppliers

  resources :orders

  resources :products

  resources :suppliers

  resources :groups

  resources :units

  devise_for :users
  resources :users

  get '/orders/open/:id', to: 'orders#open'

#  match ':controller(/:action(/:id))', :via => [ :get, :post] 

  root to: 'visitors#index'
end

app/models/group.rb
class Group < ActiveRecord::Base
	scope :active, lambda { where(:active => true) }
	has_many :units
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
	scope :sort, lambda { order('date DESC') }
	has_many :order_suppliers
end

app/models/order_supplier.rb
class OrderSupplier < ActiveRecord::Base
	scope :sort, lambda { order('order_id, position ASC') }

	belongs_to :order
	belongs_to :supplier

	acts_as_list :scope => :order
end

app/models/product.rb
class Product < ActiveRecord::Base
	scope :active, lambda { where(:active => true) }
	belongs_to :supplier
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	scope :active, lambda { where(:active => true) }
	scope :sort, lambda { order('name ASC') }
	has_many :products
end

app/models/unit.rb
class Unit < ActiveRecord::Base
	scope :active, lambda { where(:active => true) }
	belongs_to :group
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :unit
	scope :active, lambda { where(:active => true) }
	scope :sort, lambda { order('unit_id ASC') }

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
	before_action :set_group, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    authorize User
    @groups = Group.all
		@units = Unit.all
    respond_with(@groups)
  end

  def show
    authorize User
		@units = Unit.all
    respond_with(@group)
  end

  def new
    authorize User
		@units = Unit.all
    @group = Group.new
    respond_with(@group)
  end

  def edit
		@units = Unit.all
  end

  def create
    authorize User
    @group = Group.new(group_params)
    flash[:notice] = 'Group was successfully created.' if @group.save
    respond_with(@group)
  end

  def update
    authorize User
    flash[:notice] = 'Group was successfully updated.' if @group.update(group_params)
    respond_with(@group)
  end

  def destroy
    authorize User
    @group.destroy
    respond_with(@group)
  end

  private
    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :email, :telefone, :active, :dealtype, :note, :address, :error_unit_id, :acounting_unit_id, :bill_unit_id, :sw_unit_id, :acount_id)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @items = Item.all
    respond_with(@items)
  end

  def show
    respond_with(@item)
  end

  def new
    @item = Item.new
    respond_with(@item)
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    @item.save
    respond_with(@item)
  end

  def update
    @item.update(item_params)
    respond_with(@item)
  end

  def destroy
    @item.destroy
    respond_with(@item)
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:order_id, :product_id, :supplier_id, :name, :note, :minall, :mingroup, :minunit, :kgxunit, :unittype, :price)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:open, :show, :edit, :update, :destroy]

  respond_to :html

  def index
    @orders = Order.sort
    respond_with(@orders)
  end

  def open
		@suppliers=OrderSupplier.select(:supplier_id).where(:order_id=>params[:id])
		@products=Product.where(supplier_id: @suppliers, :active => true)
		@products.each do |product|
			if Item.where(:product_id=>product.id, :order_id=>params[:id]).exists?
				logger.debug(product.name)
			else
				@item=Item.new()
				@item.order_id=params[:id]
				@item.product_id=product.id
				@item.supplier_id=product.supplier_id
				@item.name=product.name
				@item.note=product.note
				@item.minall=product.minall
				@item.mingroup=product.mingroup
				@item.kgxunit=product.kgxunit
				@item.unittype=product.unittype
				@item.price=product.price
				@item.save
				logger.debug(product.name+ 'new')
			end
		end
 		if @order.state!='Open'
			@order.state='Open'
			if @order.save
	      format.html { redirect_to orders_url, notice: 'Order was successfully updated.' }
	      format.json { head :no_content }
			end
		end
	end

  def show
    respond_with(@order)
  end

  def new
    @order = Order.new
    respond_with(@order)
  end

  def edit
  end

  def create
    @order = Order.new(order_params)
    @order.save
    respond_with(@order)
  end

  def update
    @order.update(order_params)
    respond_with(@order)
  end

  def destroy
    @order.destroy
    respond_with(@order)
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:state, :date, :requested, :received, :priceini, :priceend)
    end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_unit, only: [:show, :edit, :update, :destroy]
	before_action :set_group, only: [:index, :new]

  respond_to :html

  def index
    authorize User
		if params[:group_id]
			@units = Group.find(params[:group_id]).units
		else
	    @units = Unit.all
		end
    respond_with(@units)
  end

  def show
    authorize User
    respond_with(@unit)
  end

  def new
    authorize User
    @unit = Unit.new(:group_id=>params[:group_id])
    respond_with(@unit)
  end

  def edit
  end

  def create
    authorize User
    @unit = Unit.new(unit_params)
    flash[:notice] = 'Unit was successfully created.' if @unit.save
    respond_with(@unit)
  end

  def update
    authorize User
    flash[:notice] = 'Unit was successfully updated.' if @unit.update(unit_params)
    respond_with(@unit)
  end

  def destroy
    authorize User
    @unit.destroy
    respond_with(@unit)
  end

  private
    def set_unit
      @unit = Unit.find(params[:id])
    end

    def set_group
      @group = Group.find(params[:group_id]) if params[:group_id]
    end


    def unit_params
      params.require(:unit).permit(:group_id, :name, :email, :telefone, :active, :note, :account_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized

  def index
		@units = Unit.all
		if params[:unit_id]
			@users = Unit.find(params[:unit_id]).users
		else
	    @users = User.sort
		end
    authorize User
  end

  def show
    authorize @user
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    authorize @user
    @user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def set_unit
      @unit = Unit.find(params[:unit_id])
    end

		def secure_params
		  params.require(:user).permit(:name, :surname, :active, :role, :telephone, :unit_id)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
				<li><%= link_to 'Users', users_path %></li>
				<li><%= link_to 'Units', units_path %></li>
        <li><%= link_to 'Groups', groups_path %></li>
        <li class="divider"></li>
				<li><%= link_to 'Products', products_path %></li>
				<li><%= link_to 'Suppliers', suppliers_path %></li>
        <li class="divider"></li>
        <li><a href="#">One more separated link</a></li>
      </ul>
    </li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Arac1" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Arac1" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>